PlayPickUp/pickup-ui

packages/core/src/Paper/Paper.test.tsx, packages/core/src/Paper/__snapshots__/Paper.test.tsx.snap, packages/core/src/Paper/index.tsx, packages/core/src/index.ts, packages/core/src/types/index.ts, playground/src/App/index.tsx
Adds a simple `Paper` component for a more consistent styling across our platform.
=> Add Paper component

packages/core/src/Hero/Hero.test.tsx, packages/core/src/Hero/__snapshots__/Hero.test.tsx.snap, packages/core/src/Hero/index.tsx, packages/core/src/index.ts, packages/core/src/types/index.ts, playground/src/App/index.tsx, stories/Hero.stories.tsx, yarn.lock
=> feat(ui): added hero component to ui

packages/core/src/ProgressButton/ProgressButton.test.tsx, packages/core/src/ProgressButton/__snapshots__/ProgressButton.test.tsx.snap, packages/core/src/ProgressButton/index.tsx, packages/core/src/ThemeProvider/defaultTheme.ts, packages/core/src/index.ts, packages/core/src/types/index.ts, playground/src/App/index.tsx, stories/ProgressButton.stories.tsx
Marketplace progress button to redeem prizes
=> feat(marketplace): added progress button

packages/core/src/Card/Card.test.tsx, packages/core/src/Card/__snapshots__/Card.test.tsx.snap, packages/core/src/Card/index.tsx, packages/core/src/index.ts, packages/core/src/types/index.ts, playground/src/App/index.tsx, stories/Card.stories.tsx
=> feat(marketplace): created card component

packages/core/src/Dropdown/Dropdown.test.tsx, packages/core/src/Dropdown/__snapshots__/Dropdown.test.tsx.snap, packages/core/src/Dropdown/index.tsx, packages/core/src/index.ts, packages/core/src/types/index.ts, playground/src/App/index.tsx, stories/Dropdown.stories.tsx
Moved the Dropdown component from Affiliate to UI (it's called Select in Affliate but we already have a component under that name so I'm calling this Dropdown)
=> feat(ui): moved dropdown from affiliate repo

stories/Multiselect.stories.tsx
Added MultiSelect component to Storybook under Forms.
=> fix(Storybook): Add MultiSelect to Storybook, closes #108

stories/Select.stories.tsx
Added the Select component to Storybook under Forms
=> fix(Storybook): Add Select to Storybook, close #107

packages/core/package.json, packages/core/src/ProgressButton/index.tsx, packages/core/src/types/index.ts, playground/src/App/index.tsx, stories/ProgressButton.stories.tsx, yarn.lock
A few adjustments to the progress button so that it works in Marketplace
=> fix(ui): fix progress button for new marketplace, close #148

packages/core/src/Chip/Chip.test.tsx, packages/core/src/Chip/__snapshots__/Chip.test.tsx.snap, packages/core/src/Chip/index.tsx
Added tests for the Chip component.
=> feat (Chip): Chip tests, closes #152

packages/core/src/FormError/FormError.test.tsx, packages/core/src/FormError/__snapshots__/FormError.test.tsx.snap, packages/core/src/FormError/index.tsx, playground/src/App/index.tsx
Add tests for FormError component
Closes #161
=> fix(core): Add tests for FormError

packages/icons/src/icon/Countdown.tsx, packages/icons/src/icon/Pick.tsx, packages/icons/src/index.ts, playground/src/App/index.tsx
added Pick icon and Countdown icon to playpickup/icons pacakge
=> feat(countdownIcons): added countdown icons

packages/icons/src/icon/Countdown.tsx, packages/icons/src/icon/Pick.tsx, packages/icons/src/index.ts, playground/src/App/index.tsx
following notion UI Deployment to release my countdown icons
=> feat(countdownIcons): release countdown icons

package.json, packages/core/babel.config.js, packages/core/src/MultiSelect/MultiSelect.test.tsx, packages/core/src/MultiSelect/__snapshots__/MultiSelect.test.tsx.snap, packages/core/src/MultiSelect/index.tsx, yarn.lock
Omitting, for now, one test I could not get working to test the "remove" button for a tag.
=> test(multiSelect): Add tests for MultiSelect component

packages/core/src/CheckBox/CheckBox.test.tsx, packages/core/src/CheckBox/__snapshots__/CheckBox.test.tsx.snap, packages/core/src/CheckBox/index.tsx, packages/core/src/index.ts, packages/core/src/types/index.ts, playground/src/App/index.tsx, stories/CheckBox.stories.tsx
Made checkbox for pickup ui
created two tests:
1. to check to checkbox renders without crashing and matches snapshot
2. to check that prop checked=boolean can be passed and the box can be clicked and change its checked state.
=> feat(checkbox): add checkbox to pickup ui

packages/core/package.json, packages/core/src/Button/index.tsx, packages/core/src/ThemeProvider/defaultTheme.ts, packages/core/src/types/index.ts, playground/src/App/index.tsx
Adjusted button font and disabled color to match requested new styles
=> fix(button): New button styles

packages/core/src/PickerButton/__snapshots__/PickerButton.test.tsx.snap, packages/core/src/PickerButton/index.tsx, packages/core/src/ThemeProvider/defaultTheme.ts
Updated styling for the Picker Button "picked" version based on Prop Picker QA feedback.
Also, changed the setting for `colors.purple.dark` following discussion with Chris
=> fix(pickerButton): Update dark purple, picker button colors

packages/core/src/Select/Select.test.tsx, packages/core/src/Select/__snapshots__/Select.test.tsx.snap, packages/core/src/Select/index.tsx
Also removed a duplicate test in MultiSelect
=> test(select): Make tests for Select component

packages/core/src/NestedInput/index.tsx, playground/src/App/index.tsx
make input fontSize 16 for nested input, this fixs ios zoom in on signin.
To test you will have to connect to local from browser stack
=> fix(nestedinput): adjust input font size to be min 16px

packages/core/src/NestedInput/NestedInput.test.tsx, packages/core/src/NestedInput/__snapshots__/NestedInput.test.tsx.snap, packages/core/src/NestedInput/index.tsx
Testing all versions of the NestedInput component. On this current version, this means covering props for:
- Two versions of the input field (`usePhoneNumber` and default)
- Two versions of the button (`useSubmit` true and false)
=> test(nestedInput): Test all versions of NestedInput

packages/core/src/PickerButton/PickerButton.test.tsx
=> test(pickerButton): Enhance PickerButton tests

packages/core/src/TextArea/TextArea.test.tsx, packages/core/src/TextArea/__snapshots__/TextArea.test.tsx.snap, packages/core/src/TextArea/index.tsx
Added and enhanced textarea component tests for all props
=> fix(textarea): add and enhance tests for textarea component

packages/core/src/Slider/Slider.test.tsx
=> Feat(core): slider test upgrades (#299)

packages/core/package.json, packages/core/src/Ads/Ads.test.tsx, packages/core/src/Ads/__snapshots__/Ads.test.tsx.snap, packages/core/src/Ads/index.tsx, packages/core/src/index.ts, packages/core/src/types/index.ts, playground/src/App/index.tsx, stories/Ads.stories.tsx, yarn.lock
#310 
https://app.zenhub.com/workspaces/pickup-5ee6cbe39ef1ca001fefe69b/issues/playpickup/pickup-ui/310
=> feature(adManager): Create Ad Component, eng-85

packages/core/package.json, packages/core/src/Ads/Ads.test.tsx, packages/core/src/Ads/__snapshots__/Ads.test.tsx.snap, packages/core/src/Ads/index.tsx, packages/core/src/index.ts, packages/core/src/types/index.ts, playground/src/App/index.tsx, stories/Ads.stories.tsx, yarn.lock
=> release 3-17-22

packages/core/src/CheckBox/__snapshots__/CheckBox.test.tsx.snap, packages/core/src/CheckBox/index.tsx, packages/core/src/types/index.ts, stories/CheckBox.stories.tsx
curious if this will link: 
https://linear.app/pickup/issue/ENG-191/release-ui
=> Release 3/24/22 💅, eng-191

packages/core/src/Button/__snapshots__/Button.test.tsx.snap, packages/core/src/Button/index.tsx, packages/core/src/FeedCard/FeedCard.test.tsx, packages/core/src/FeedCard/__snapshots__/FeedCard.test.tsx.snap, packages/core/src/NestedInput/NestedInput.test.tsx, packages/core/src/NestedInput/__snapshots__/NestedInput.test.tsx.snap, packages/core/src/NestedInput/index.tsx, playground/src/App/index.tsx
adjusted button
above 320 px width
below 320px
=> feature(nestedinput): make button below input on less than 320px,eng-222

packages/core/src/Hero/Hero.test.tsx, packages/core/src/Hero/PartnerLogos.tsx, packages/core/src/Hero/__snapshots__/Hero.test.tsx.snap, packages/core/src/Hero/index.tsx, packages/core/src/types/index.ts, playground/src/App/index.tsx, stories/Hero.stories.tsx
TIL this exists: https://picsum.photos/
This is in use in the Playground. You can use that to change photo sizes or add/remove photos to play with different arrangements.
=> feature(hero): Add optional logos to bottom of Hero
